// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGvPmkyWBe0so-X2qZ6fNHHUNQRo4aA8c',
    appId: '1:829136781785:web:cfeedbf6d4c21b8a77d9c8',
    messagingSenderId: '829136781785',
    projectId: 'flutter-firebase-ae25f',
    authDomain: 'flutter-firebase-ae25f.firebaseapp.com',
    storageBucket: 'flutter-firebase-ae25f.appspot.com',
    measurementId: 'G-TTQYRM85X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIiNdtOYcHeS8VxoVbbwVes583p_yGRAY',
    appId: '1:829136781785:android:370f04aaac21e86977d9c8',
    messagingSenderId: '829136781785',
    projectId: 'flutter-firebase-ae25f',
    storageBucket: 'flutter-firebase-ae25f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATaJp2urAVPnqFwtcbklEXsMGRsYMB_fQ',
    appId: '1:829136781785:ios:057ecfcd766c17cf77d9c8',
    messagingSenderId: '829136781785',
    projectId: 'flutter-firebase-ae25f',
    storageBucket: 'flutter-firebase-ae25f.appspot.com',
    iosClientId: '829136781785-p0hldanhfkcebme2v3dvsdku3tf47aak.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
